# FAIL

fn f(x: int) -> int {
  let x = 10
  return x
}
